C:
  - "**/*.c"
C-Plus-Plus:
  - "**/*.cpp"
  - "**/*.cc"
  - "**/*.cxx"
C-Sharp:
  - "**/*.cs"
Go:
  - "**/*.go"
Java:
  - "**/*.java"
JavaScript:
  - "**/*.js"
Python:
  - "**/*.py"
Q-Sharp:
  - "**/*.qs"
Dart:
  - "**/*.dart"
enhancement:
  - ".github/**"
  - "**/*.md"
